before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    main: ./cmd/luks2crypt
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
