only-deploy-tags: &only-deploy-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /v[0-9]+(\.[0-9]+)*(-.*)*/

version: 2.1
executors:
  golang:
    docker:
      - image: cimg/go:1.16

commands:
  setup-image:
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y libcryptsetup-dev

jobs:
  lint:
    executor: golang
    steps:
      - setup-image
      - run: make lint
  test:
    executor: golang
    steps:
      - setup-image
      - run: make test
  build:
    executor: golang
    steps:
      - setup-image
      - run: make build
  publish-github-release:
    executor: golang
    steps:
      - checkout
      - run: make deploy

workflows:
  version: 2
  build-test-workflow:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
  deploy-workflow:
    jobs:
      - test:
          <<: *only-deploy-tags
      - build:
          <<: *only-deploy-tags
          requires:
            - test
      - publish-github-release:
          <<: *only-deploy-tags
          requires:
            - build
