name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'stable' ]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
      with:
        # only enable the cache if the ref is not a tag
        cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libcryptsetup-dev

    - name: Lint
      run: make lint

    - name: Test
      run: make test
