name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'stable' ]

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libcryptsetup-dev

    - name: Lint
      run: make lint

    - name: Test
      run: make test
